--- #YAML:1.0
name:                Bundle-DependenciesCatalyst
version:             0.02
abstract:            installs non-Catalyst prereqs
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Kevin W. Henwood <Khen1950fx@aol.com>
